### ISSUE TITLE
Cannot find module 'node-haste/lib/DependencyGraph/docblock.js' 

### ISSUE THREAD

**Issue by hzy00** [ctripcorp/moles-packer#16]
都没人解决问题的么？看这些issue一个都没有回答。
打包直接报错Cannot find module 'node-haste/lib/DependencyGraph/docblock.js'

**Comment by WPCWEG** [comment]
这个问题很简单啊，你没有安装node-haste这个库，你运行 npm install -g node-haste,就可以了。缺少文件是因为没有。

**Comment by hzy00** [comment]
确实如此 3Q~
